'use strict';

// Node-8-compatible post-restart half of the A-05 process test.  Credentials
// and token ids are read from the private initial result generated by
// sdkMatrixClient.cjs; the endpoint comes from the newly started server.

var assert = require('assert');
var crypto = require('crypto');
var fs = require('fs');
var path = require('path');

var metadata = JSON.parse(fs.readFileSync(process.env.A05_METADATA, 'utf8'));
var initial = JSON.parse(fs.readFileSync(process.env.A05_INITIAL_RESULT, 'utf8'));
var clientRoot = process.env.A05_CLIENT_ROOT;
var OOBE = require(path.join(clientRoot, 'clients/oobe.js'));
var Account = require(path.join(clientRoot, 'clients/account.js'));
var Loop = require(path.join(clientRoot, 'clients/loop.js'));
var rows = [];

function client(Type, endpoint, credentials) {
  return new Type({
    endpoint: endpoint,
    region: 'global',
    credentials: credentials,
    maxRetries: 0,
    httpOptions: { timeout: 10000, connectTimeout: 3000 },
  });
}

function invoke(service, method, params, unauthenticated) {
  var request = unauthenticated
    ? service.makeUnauthenticatedRequest(method, params)
    : service[method](params);
  return new Promise(function (resolve) {
    var settled = false;
    function finish(value) {
      if (settled) return;
      settled = true;
      resolve(value);
    }
    request.send(function (error, data) {
      if (error) {
        return finish({
          error: {
            name: error.name,
            code: error.code,
            statusCode: error.statusCode,
            message: error.message,
          },
          data: null,
        });
      }
      finish({ error: null, data: data === undefined ? null : data });
    });
    request.on('error', function () {});
  });
}

function pass(face, name, details) {
  rows.push({ face: face, name: name, passed: true, details: details || undefined });
}

function hash(value) {
  return crypto.createHash('sha256').update(String(value)).digest('hex');
}

function wire(value) {
  if (Array.isArray(value)) return value.map(wire);
  if (!value || typeof value !== 'object') return value;
  var fields = Object.keys(value).sort();
  if (value.accessKeyId || value.secretAccessKey) {
    return {
      fields: fields,
      credentialHash: hash(String(value.accessKeyId || '') + '\0' + String(value.secretAccessKey || '')),
      serviceMode: value.serviceMode,
    };
  }
  if (value.token) return { fields: fields, tokenHash: hash(value.token), expires: value.expires };
  var out = {};
  fields.forEach(function (field) { out[field] = wire(value[field]); });
  return out;
}

function expectError(face, name, result, code, statusCode) {
  assert(result && result.error, face + ' ' + name + ' unexpectedly succeeded');
  assert.strictEqual(result.error.code, code, face + ' ' + name + ' error code');
  if (statusCode !== undefined) assert.strictEqual(result.error.statusCode, statusCode, face + ' ' + name + ' HTTP status');
  pass(face, name, { error: { code: result.error.code, statusCode: result.error.statusCode, message: result.error.message } });
}

function expectSuccess(face, name, result) {
  assert(result && !result.error, face + ' ' + name + ' failed: ' + JSON.stringify(result && result.error));
  pass(face, name, { statusCode: 200, wire: wire(result.data) });
  return result.data;
}

function checkPersistedRobot(fixture, issued, kind, expectedFriendlyId) {
  var face = fixture.face;
  var endpoint = metadata[face + 'Endpoint'];
  var account = client(Account, endpoint, issued);
  var loop = client(Loop, endpoint, issued);
  return invoke(account, 'get', {})
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART Account.Get ' + kind, result);
      assert(Array.isArray(data));
      assert.strictEqual(data.length, 1);
      assert.strictEqual(typeof data[0].id, 'string');
      pass(face, 'RESTART issued ' + kind + ' account credential accepted', { accountId: data[0].id });
      return invoke(loop, 'list', {});
    })
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART Loop.List ' + kind, result);
      assert(Array.isArray(data));
      assert.strictEqual(data.length, 1, face + ' ' + kind + ' robot sees one live loop');
      assert.strictEqual(data[0].robotFriendlyId, expectedFriendlyId);
      pass(face, 'RESTART issued ' + kind + ' loop credential accepted', { loopId: data[0].id, robotFriendlyId: data[0].robotFriendlyId });
    });
}

function runFace(fixture, initialFace) {
  var face = fixture.face;
  var endpoint = metadata[face + 'Endpoint'];
  var normal = client(OOBE, endpoint, fixture.owner);
  var ordinary = initialFace.ordinary;
  var replacement = initialFace.replacement;
  var service = initialFace.service;

  // Account and Loop SDK calls exercise the credentials that were issued by
  // SetupRobot before the process boundary.  Account.Get is intentionally
  // checked before Loop.List so an identity failure cannot be hidden by a
  // route projection.
  return checkPersistedRobot(fixture, ordinary, 'ordinary', fixture.ordinaryRobotId)
    .then(function () { return checkPersistedRobot(fixture, replacement, 'replacement', fixture.replacementRobotId); })
    .then(function () { return checkPersistedRobot(fixture, service, 'service-mode', fixture.serviceRobotId); })
    // Consumed setup, replacement, reconnect, and service tokens remain
    // complete after the process restart. These checks are unauthenticated,
    // matching the original SDK's public OOBE calls.
    .then(function () { return invoke(normal, 'getStatus', { token: fixture.setupToken }, true); })
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART GetStatus consumed setup token', result);
      assert.strictEqual(data.complete, true);
      return invoke(normal, 'setupRobot', { token: fixture.setupToken, id: fixture.ordinaryRobotId }, true);
    })
    .then(function (result) {
      expectError(face, 'RESTART FALSIFY consumed setup token replay', result, 'TOKEN_NOT_FOUND', 404);
      return invoke(normal, 'getStatus', { token: fixture.replacementToken }, true);
    })
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART GetStatus consumed replacement token', result);
      assert.strictEqual(data.complete, true);
      return invoke(normal, 'getStatus', { token: fixture.reconnectToken }, true);
    })
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART GetStatus consumed reconnect token', result);
      assert.strictEqual(data.complete, true);
      return invoke(normal, 'reconnectRobot', { token: fixture.reconnectToken, id: fixture.ordinaryRobotId }, false);
    })
    .then(function (result) {
      // Named falsification across the restart: a token restored from an old
      // snapshot would make this replay succeed or return a different error.
      expectError(face, 'RESTART FALSIFY consumed reconnect token replay', result, 'TOKEN_NOT_FOUND', 404);
      return invoke(normal, 'getStatus', { token: initialFace.serviceToken }, true);
    })
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART GetStatus consumed service token', result);
      assert.strictEqual(data.complete, true);
      return invoke(normal, 'getStatus', { token: fixture.expiredToken }, true);
    })
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART GetStatus expired token', result);
      assert.strictEqual(data.complete, true);
      return invoke(normal, 'setupRobot', { token: fixture.expiredToken, id: fixture.ordinaryRobotId }, true);
    })
    .then(function (result) {
      expectError(face, 'RESTART FALSIFY expired token remains expired', result, 'TOKEN_EXPIRED', 401);
      // The token minted by PrepareRobot was deliberately left unused before
      // shutdown.  Its pending state and one-time transition must survive the
      // orderly service restart.
      return invoke(normal, 'getStatus', { token: initialFace.restartToken }, true);
    })
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART GetStatus newly issued token remains pending', result);
      assert.strictEqual(data.complete, false);
      return invoke(normal, 'reconnectRobot', { token: initialFace.restartToken, id: fixture.ordinaryRobotId }, false);
    })
    .then(function (result) {
      var data = expectSuccess(face, 'RESTART ReconnectRobot newly issued token', result);
      assert.strictEqual(data.result, 'Command accepted');
      return invoke(normal, 'reconnectRobot', { token: initialFace.restartToken, id: fixture.ordinaryRobotId }, false);
    })
    .then(function (result) {
      expectError(face, 'RESTART FALSIFY newly issued token replay', result, 'TOKEN_NOT_FOUND', 404);
      return { face: face, checks: rows.filter(function (row) { return row.face === face; }).length };
    });
}

Promise.resolve()
  .then(function () {
    var byFace = {};
    initial.faces.forEach(function (face) { byFace[face.face] = face; });
    var faces = [];
    return metadata.fixtures.reduce(function (chain, fixture) {
      return chain.then(function () { return runFace(fixture, byFace[fixture.face]); })
        .then(function (face) { faces.push(face); });
    }, Promise.resolve()).then(function () { return faces; });
  })
  .then(function (faces) {
    var result = {
      passed: true,
      phase: metadata.phase,
      runtime: process.version,
      clientVersion: require(path.join(clientRoot, 'package.json')).version,
      candidateRevision: metadata.candidateRevision,
      faces: faces,
      rows: rows,
      checks: rows.length,
    };
    fs.writeFileSync(process.env.A05_RESULT, JSON.stringify(result, null, 2) + '\n', { mode: 0o600 });
    process.stdout.write(JSON.stringify({ passed: true, phase: metadata.phase, checks: rows.length, runtime: process.version, clientVersion: result.clientVersion }) + '\n');
  })
  .catch(function (error) {
    var result = {
      passed: false,
      phase: metadata.phase,
      runtime: process.version,
      clientVersion: require(path.join(clientRoot, 'package.json')).version,
      candidateRevision: metadata.candidateRevision,
      rows: rows,
      checks: rows.length,
      error: { name: error.name, code: error.code, statusCode: error.statusCode, message: error.message, stack: error.stack },
    };
    try { fs.writeFileSync(process.env.A05_RESULT, JSON.stringify(result, null, 2) + '\n', { mode: 0o600 }); } catch (writeError) {}
    process.stderr.write((error && error.stack) || String(error));
    process.stderr.write('\n');
    process.exit(1);
  });
