#!/usr/bin/env python3
"""Build the API update using an existing Compose container's GPU image.

Run on the GPU host. By default this only prepares the image and a Compose
wrapper; --apply also recreates the ASR service. Other services are untouched.
Only Python 3.7+ (standard library) and Docker Compose are required.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path, PurePosixPath
import shlex
import subprocess
import sys


VERSION = "0.3.0"
MARKER = "# Generated by Parakeet tools/update-compose.py"


class UpdateError(Exception):
    pass


def shell_join(command: list[str]) -> str:
    # shlex.join was added in Python 3.8; some WSL distributions are older.
    return " ".join(shlex.quote(argument) for argument in command)


def run(command: list[str], *, cwd: Path, capture: bool = False) -> str:
    result = subprocess.run(command, cwd=cwd, text=True,
                            stdout=subprocess.PIPE if capture else None,
                            stderr=subprocess.PIPE if capture else None)
    if result.returncode:
        # Never print captured config/inspect output: it can contain secrets.
        if capture and result.stderr:
            print(result.stderr.strip(), file=sys.stderr)
        raise UpdateError(f"Command failed: {shell_join(command)}")
    return result.stdout or ""


def yaml_json(value: object) -> str:
    # JSON is valid YAML. Escape dollars against Compose interpolation as well.
    return json.dumps(value).replace("$", "$$")


def code_mounts(service: dict, source: Path) -> list[dict]:
    """Prevent old bind mounts or volumes from hiding the updated image code."""
    overrides = {}
    for mount in service.get("volumes", []):
        target = PurePosixPath(mount["target"])
        app = PurePosixPath("/srv/app")
        if target == app or target in app.parents:
            overrides[str(app)] = {
                "type": "bind", "source": str(source / "app"),
                "target": str(app), "read_only": True,
            }
        elif app in target.parents:
            local = source / "app" / str(target.relative_to(app))
            if not local.exists():
                raise UpdateError(f"A mount masks unknown application code: {target}")
            overrides[str(target)] = {
                "type": "bind", "source": str(local),
                "target": str(target), "read_only": True,
            }
    return list(overrides.values())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--container", default="parakeet-asr-gpu",
                        help="existing ASR container, running or stopped")
    parser.add_argument("--image", default=f"parakeet-asr:{VERSION}")
    parser.add_argument("--apply", action="store_true",
                        help="also recreate the ASR service from the verified image")
    args = parser.parse_args()
    source = Path(__file__).resolve().parents[1]
    for required in ("Dockerfile.update", "app/inference.py", "app/server.py"):
        if not (source / required).is_file():
            raise UpdateError(f"Updated source is missing: {source / required}")

    inspect = json.loads(run(["docker", "inspect", "--type", "container",
                              args.container], cwd=Path.cwd(), capture=True))[0]
    labels = inspect["Config"].get("Labels") or {}
    prefix = "com.docker.compose."
    service_name = labels.get(prefix + "service")
    project = labels.get(prefix + "project")
    workdir = Path(labels.get(prefix + "project.working_dir", str(Path.cwd())))
    files = labels.get(prefix + "project.config_files", "").split(",")
    if not service_name or not project or not all(files):
        raise UpdateError("The existing container must have Docker Compose labels.")
    if not workdir.is_dir():
        raise UpdateError(f"Existing Compose directory is missing: {workdir}")

    override = workdir / f"compose.parakeet-{VERSION}.yaml"
    wrapper = workdir / f"parakeet-compose-{VERSION}.sh"
    files = [str(Path(name).resolve()) if Path(name).is_absolute()
             else str((workdir / name).resolve()) for name in files]
    # Reruns use the original files, without layering our generated file twice.
    files = [name for name in files if Path(name) != override]
    if not files:
        raise UpdateError("Cannot identify the original Compose configuration.")
    compose = ["docker", "compose", "--project-directory", str(workdir),
               "--project-name", project]
    environment_files = labels.get(prefix + "project.environment_file", "")
    for name in environment_files.split(",") if environment_files else []:
        compose.extend(["--env-file", name])
    for name in files:
        if not Path(name).is_file():
            raise UpdateError(f"Original Compose file is missing: {name}")
        compose.extend(["-f", name])
    config = json.loads(run(compose + ["config", "--format", "json"],
                            cwd=workdir, capture=True))
    services = config.get("services", {})
    if service_name not in services:
        raise UpdateError(f"Existing Compose configuration has no {service_name!r} service.")
    old = services[service_name]
    backend = old.get("environment", {}).get("PARAKEET_BACKEND") or "nemo"
    if backend.strip().lower() != "nemo":
        raise UpdateError("This update is for the NeMo GPU backend.")

    # Preserve the exact resident GPU stack, regardless of its original tag.
    image_id = inspect["Image"]
    image_hash = image_id.split(":", 1)[-1]
    base = f"parakeet-asr:working-base-{image_hash[:12]}"
    build = {"context": str(source), "dockerfile": "Dockerfile.update",
             "args": {"PARAKEET_BASE_IMAGE": base}}
    command = ["uvicorn", "app.server:app", "--host", "0.0.0.0",
               "--port", "6972", "--workers", "1"]
    mounts = code_mounts(old, source)
    content = (f"{MARKER}\nservices:\n  {yaml_json(service_name)}:\n"
               f"    image: {yaml_json(args.image)}\n"
               "    pull_policy: never\n"
               f"    build: !override {yaml_json(build)}\n"
               "    working_dir: /srv\n"
               "    entrypoint: []\n"
               f"    command: {yaml_json(command)}\n")
    if mounts:
        content += f"    volumes: {yaml_json(mounts)}\n"
    for path in (override, wrapper):
        if path.exists() and MARKER not in path.read_text():
            raise UpdateError(f"Refusing to overwrite an unrelated file: {path}")
    override.write_text(content)
    updated_compose = compose + ["-f", str(override)]
    merged = json.loads(run(updated_compose + ["config", "--format", "json"],
                            cwd=workdir, capture=True))
    new = merged["services"][service_name]
    allowed = {"image", "build", "pull_policy", "command", "entrypoint",
               "working_dir", "volumes"}
    for key in set(old) | set(new):
        if key not in allowed and old.get(key) != new.get(key):
            raise UpdateError(f"Unexpected change to existing Compose setting: {key}")
    if new.get("build") != build or new.get("image") != args.image:
        raise UpdateError("Compose did not select the new image and update Dockerfile.")
    new_mounts = {mount["target"]: mount for mount in new.get("volumes", [])}
    replaced = {mount["target"] for mount in mounts}
    for mount in old.get("volumes", []):
        if mount["target"] not in replaced and new_mounts.get(mount["target"]) != mount:
            raise UpdateError(f"Unexpected change to existing volume: {mount['target']}")

    print(f"Updating Compose service {service_name!r} in project {project!r}.", flush=True)
    print(f"Base: existing container image {image_id[:19]}; GPU/cache settings preserved.",
          flush=True)
    if mounts:
        print("Redirecting mounts that hide /srv/app to the copied 0.3.0 code.", flush=True)
    run(["docker", "image", "tag", image_id, base], cwd=workdir)
    run(["docker", "build", "-f", str(source / "Dockerfile.update"),
         "--build-arg", f"PARAKEET_BASE_IMAGE={base}",
         "-t", args.image, str(source)], cwd=workdir)
    version = run(["docker", "run", "--rm", "--entrypoint", "python",
                   "--workdir", "/srv", "--env", "PARAKEET_BACKEND=nemo", args.image,
                   "-c", "from app.server import API_VERSION; print(API_VERSION)"],
                  cwd=workdir, capture=True).strip().splitlines()
    if not version or version[-1] != VERSION:
        raise UpdateError(f"Built image does not report API {VERSION}.")

    up = ["up", "-d", "--no-deps", "--pull", "never", service_name]
    script = (f"#!/bin/sh\n{MARKER}\nset -eu\ncd {shlex.quote(str(workdir))}\n"
              f"if [ \"$#\" -eq 0 ]; then\n  set -- {shell_join(up)}\nfi\n"
              f"exec {shell_join(updated_compose)} \"$@\"\n")
    wrapper.write_text(script)
    wrapper.chmod(0o755)
    print(f"Verified image API {VERSION}.", flush=True)
    print(f"For future Compose commands, use {wrapper} (it includes the update override).",
          flush=True)
    if args.apply:
        run(updated_compose + up, cwd=workdir)
        print(f"ASR container recreated. Wait for model loading, then check /healthz for {VERSION}.")
    else:
        print(f"Prepared without restarting. To start the updated ASR:\n{shlex.quote(str(wrapper))}")


if __name__ == "__main__":
    try:
        main()
    except (UpdateError, OSError, ValueError, KeyError) as error:
        print(f"Update stopped: {error}", file=sys.stderr)
        sys.exit(1)
