// ROM service (ROM_20171011) — the remote-operation certificate exchange.
//
// This is the cloud half of Jibo's Remote Operation Mode. Three operations:
//   Create       (loop owner) mints a matched self-signed server/client pair for a robot
//   SetupServer  (robot)      publishes the robot's IP payload and marks the pair deployed
//   SetupClient  (loop owner) hands the client cert + PKCS#12 + robot payload to the operator
//
// Source: jiborobot/srv-rom-ws (the archived ROM cloud service, the one thing that answers
// ROM_20171011):
//   src/handlers/rom.handler.ts     create / setupServer / setupClient mapping + Joi payloads
//   src/controllers/rom.ctrl.ts     ownership, master switch, cert lifecycle, selfsigned generation
//   src/schemes/certificate.ts      Certificate document { _id, client, complete, created, payload, server }
//   src/clients/account.client.ts   Loop_2016.ListLoops     (ownership)
//   src/clients/robot.client.ts     Robot_20160225.GetRobot (master switch: payload.remoteEnabled)
//   src/errors/rom.ts               the error catalog reproduced verbatim below
//   config/config.json              mongo-backed store; SNS topic jibo-events-legacy
// Wire shapes: jiborobot/srv-jibo-server-client@155d20a8102960b2aeb89c197bdf04dc1f1fc344/
//   apis/rom-2017-10-11.normal.json (CreateRequest/CreateResponse/ClientRequest/ClientResponse/
//   Payload/ServerResponse).
//
// Certificate material is generated by the same libraries the original used — selfsigned
// (with clientCertificate:true) + node-forge — so the keys, certificate chain shape, SHA-1
// colon-hex fingerprints, one-day server validity and PKCS#12 (empty passphrase, 3DES) are
// genuinely reproducible. What is NOT reproducible: the original SNS RomConnectionRequested
// delivery and the robot-side ROM websocket session (LAN hardware), both recorded as
// divergence candidates.

import { promisify } from 'node:util';
import forge from 'node-forge';
import selfsigned from 'selfsigned';
import { DefaultPort } from '@phoenix/contracts';
import { sendAmz, sendAmzError, accessKeyIdFromAuth, ValidationException, AMZ_JSON } from './awsJson.js';

const generateAsync = promisify(selfsigned.generate);

/** CERTIFICATE_LIFETIME (rom.ctrl.ts) — the server certificate validity window, in days. */
export const CERTIFICATE_LIFETIME_DAYS = 1;

/** errors/rom.ts, verbatim: code, message and HTTP status. */
export const ROM_ERRORS = Object.freeze({
  ROBOT_NOT_OWNED: { code: 'ROBOT_NOT_OWNED', message: 'You must own specified robot to create certificate', statusCode: 403 },
  ROBOT_NOT_FOUND: { code: 'ROBOT_NOT_FOUND', message: 'Specified robot is not found', statusCode: 404 },
  REMOTE_MODE_DISABLED: { code: 'REMOTE_MODE_DISABLED', message: 'Remote mode is disabled for specified robot', statusCode: 403 },
  ROBOT_MUST_CALL: { code: 'ROBOT_MUST_CALL', message: 'Only robot is allowed to call this method', statusCode: 403 },
  CERTIFICATE_NOT_FOUND: { code: 'CERTIFICATE_NOT_FOUND', message: 'Certificate not found', statusCode: 404 },
  CERTIFICATE_NOT_DEPLOYED: { code: 'CERTIFICATE_NOT_DEPLOYED', message: 'Certificate not deployed', statusCode: 404 },
});

/** Thrown by the controller; carries the wire error object the handler serializes. */
export class RomError extends Error {
  constructor(error) {
    super(error.message);
    this.name = 'RomError';
    this.romError = error;
    this.statusCode = error.statusCode;
  }
}

const fail = (key) => { throw new RomError(ROM_ERRORS[key]); };

const fingerprintHex = (cert) => forge.md.sha1
  .create()
  .update(forge.asn1.toDer(forge.pki.certificateToAsn1(cert)).getBytes())
  .digest()
  .toHex()
  .match(/.{2}/g)
  .join(':');

/**
 * Mint one matched certificate pair exactly like rom.ctrl.ts:
 *   selfsigned.generate([{commonName:'jibo.com'}], { sha256, clientCertificate:true, days:1 })
 * The server certificate is an RSA-1024 self-signed cert valid for one day; the client
 * certificate is a separate RSA-1024 key signed by the server key, CN "John Doe jdoe123"
 * (selfsigned's default when clientCertificateCN is unset), and packaged as a PKCS#12 blob
 * (empty passphrase, 3DES) the operator client loads.
 *
 * @returns {Promise<{server: object, client: object}>} PEM/fingerprint/p12 bundles.
 */
export async function generateCertificatePair() {
  const attrs = [{ name: 'commonName', value: 'jibo.com' }];
  const container = await generateAsync(attrs, {
    algorithm: 'sha256',
    clientCertificate: true,
    days: CERTIFICATE_LIFETIME_DAYS,
  });
  const server = {
    cert: container.cert,
    fingerprint: container.fingerprint,
    private: container.private,
    public: container.public,
  };
  const clientCert = forge.pki.certificateFromPem(container.clientcert);
  const clientPk = forge.pki.privateKeyFromPem(container.clientprivate);
  const clientP12Asn1 = forge.pkcs12.toPkcs12Asn1(clientPk, clientCert, '', { algorithm: '3des' });
  const client = {
    cert: container.clientcert,
    fingerprint: fingerprintHex(clientCert),
    p12: forge.util.encode64(forge.asn1.toDer(clientP12Asn1).getBytes()),
    private: container.clientprivate,
    public: container.clientpublic,
  };
  return { client, server };
}

/**
 * In-memory stand-in for the mongoose Certificate model (schemes/certificate.ts):
 *   { _id: friendlyId, client: pemSchema, complete: Boolean,
 *     created: Date (default now), payload: { ipAddress, ipAddresses }, server: pemSchema }
 * Mongoose's `created` is a Date, and every response exposes `created.getTime()`.
 */
export class CertificateStore {
  constructor(clock = Date.now) {
    this.certificates = new Map();
    this.clock = clock;
  }

  create(doc) {
    const record = {
      _id: doc._id,
      client: doc.client,
      complete: doc.complete === undefined ? false : doc.complete,
      created: doc.created instanceof Date ? doc.created : new Date(doc.created === undefined ? this.clock() : doc.created),
      payload: doc.payload === undefined ? {} : doc.payload,
      server: doc.server,
    };
    this.certificates.set(String(record._id), record);
    return record;
  }

  findById(id) {
    if (id === undefined || id === null) return null;
    return this.certificates.get(String(id)) || null;
  }

  /** Mongoose Model.findByIdAndRemove — Create always mints a fresh pair. */
  findByIdAndRemove(id) {
    const found = this.findById(id);
    if (found) this.certificates.delete(String(id));
    return found;
  }

  save(record) {
    this.certificates.set(String(record._id), record);
    return record;
  }
}

/**
 * Certificate entity manipulation — a direct port of RomController (rom.ctrl.ts).
 * Dependencies are injected so the account/robot lookups can be a fake in tests and real
 * HTTP clients at runtime, mirroring the original's constructor(config, registry, sender).
 */
export class RomController {
  constructor({
    accountClient,
    robotClient,
    certificates = new CertificateStore(),
    onConnectionRequested = () => {},
    generatePair = generateCertificatePair,
  } = {}) {
    this.accountClient = accountClient;
    this.robotClient = robotClient;
    this.certificates = certificates;
    this.onConnectionRequested = onConnectionRequested;
    this.generatePair = generatePair;
  }

  /** rom.ctrl.ts create — loop owner mints a fresh pair; returns { created }. */
  async create({ aco, friendlyId, ownerId, req } = {}) {
    await this.checkRobotOwnership({ friendlyId, ownerId, req });
    await this.checkMasterSwitch({ friendlyId, ownerId, req });
    this.certificates.findByIdAndRemove(friendlyId);
    const { client, server } = await this.generatePair();
    const certificate = this.certificates.create({ _id: friendlyId, client, server });
    this.onConnectionRequested({ aco, certFingerprint: certificate.client.fingerprint, friendlyId });
    return { created: certificate.created.getTime() };
  }

  /** rom.ctrl.ts setupServer — the robot deploys: record its payload, mark complete. */
  async setupServer({ friendlyId, ipAddress, ipAddresses, req } = {}) {
    if (!friendlyId) fail('ROBOT_MUST_CALL');
    const certificate = this.certificates.findById(friendlyId);
    if (!certificate) fail('CERTIFICATE_NOT_FOUND');
    certificate.payload = certificate.payload || {};
    certificate.payload.ipAddress = ipAddress;
    certificate.payload.ipAddresses = ipAddresses;
    certificate.complete = true;
    this.certificates.save(certificate);
    return {
      cert: certificate.server.cert,
      created: certificate.created.getTime(),
      fingerprint: certificate.client.fingerprint,
      private: certificate.server.private,
      public: certificate.server.public,
    };
  }

  /** rom.ctrl.ts setupClient — loop owner fetches the client cert once the robot deployed. */
  async setupClient({ friendlyId, ownerId, req } = {}) {
    await this.checkRobotOwnership({ friendlyId, ownerId, req });
    const certificate = this.certificates.findById(friendlyId);
    if (!certificate) fail('CERTIFICATE_NOT_FOUND');
    if (!certificate.complete) fail('CERTIFICATE_NOT_DEPLOYED');
    return {
      cert: certificate.client.cert,
      created: certificate.created.getTime(),
      fingerprint: certificate.server.fingerprint,
      p12: certificate.client.p12,
      payload: certificate.payload,
      private: certificate.client.private,
      public: certificate.client.public,
    };
  }

  /** The caller must own a loop whose robotFriendlyId is the robot (Loop_2016.ListLoops). */
  async checkRobotOwnership({ friendlyId, ownerId, req } = {}) {
    const loops = await this.accountClient.listLoops(ownerId, req);
    const robotIsOwned = Array.isArray(loops)
      && loops.some((loop) => loop && loop.robotFriendlyId === friendlyId && loop.owner === ownerId);
    if (!robotIsOwned) fail('ROBOT_NOT_OWNED');
  }

  /** The robot's remote-access master switch (Robot_20160225.GetRobot payload.remoteEnabled). */
  async checkMasterSwitch({ friendlyId, ownerId, req } = {}) {
    const robot = await this.robotClient.getById({ friendlyId, ownerId }, req);
    if (!robot) fail('ROBOT_NOT_FOUND');
    if (!robot.payload.remoteEnabled) fail('REMOTE_MODE_DISABLED');
  }
}

// ── default clients (the original's internal service-to-service calls) ────────

const normalizeBase = (value) => {
  if (!value) return null;
  return /^https?:\/\//.test(value) ? value.replace(/\/$/, '') : `http://${String(value).replace(/\/$/, '')}`;
};

const resolveBase = (base, req) => {
  const value = typeof base === 'function' ? base(req) : base;
  return normalizeBase(value);
};

/** NET_account — the process that owns loops and identity (router.js convention). */
export function accountBaseUrl() {
  return normalizeBase(process.env.NET_account) || `http://localhost:${DefaultPort.account}`;
}

/** NET_robotread, or the classic entrypoint itself (which serves Robot_20160225). */
export function robotBaseUrl(req) {
  const configured = normalizeBase(process.env.NET_robotread);
  if (configured) return configured;
  if (req && req.headers && req.headers.host) {
    const scheme = req.socket && req.socket.encrypted ? 'https' : 'http';
    return `${scheme}://${req.headers.host}`;
  }
  return `http://localhost:${DefaultPort.classic}`;
}

async function postAmzJson(base, target, credentials, body, fetchImpl = fetch) {
  const res = await fetchImpl(`${base}/`, {
    method: 'POST',
    headers: {
      'content-type': AMZ_JSON,
      'x-amz-target': target,
      'x-amz-credentials': JSON.stringify(credentials),
    },
    body: JSON.stringify(body === undefined ? {} : body),
  });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(`${target} failed: ${res.status} ${text}`);
  }
  try { return JSON.parse(text); } catch { return text; }
}

/** AccountClient.listLoops — Loop_2016.ListLoops with the owner id in x-amz-credentials. */
export function makeAccountClient({ baseUrl = accountBaseUrl, fetchImpl = fetch } = {}) {
  return {
    async listLoops(ownerId, req) {
      const base = resolveBase(baseUrl, req);
      return postAmzJson(base, 'Loop_2016.ListLoops', { id: ownerId }, {}, fetchImpl);
    },
  };
}

/** RobotClient.getById — Robot_20160225.GetRobot with the owner id in x-amz-credentials. */
export function makeRobotClient({ baseUrl = robotBaseUrl, fetchImpl = fetch } = {}) {
  return {
    async getById({ friendlyId, ownerId }, req) {
      const base = resolveBase(baseUrl, req);
      return postAmzJson(base, 'Robot_20160225.GetRobot', { id: ownerId }, { id: friendlyId }, fetchImpl);
    },
  };
}

// ── AWS-JSON handler ─────────────────────────────────────────────────────────

/** parseCredentials: x-amz-credentials JSON; SigV4 accessKeyId is a Phoenix LAN fallback. */
function credentialsFrom(req) {
  const raw = req && req.headers ? req.headers['x-amz-credentials'] : undefined;
  if (raw) {
    try {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === 'object') return parsed;
    } catch { /* fall through */ }
  }
  const accessKeyId = accessKeyIdFromAuth(req);
  return accessKeyId ? { id: accessKeyId } : {};
}

/** Joi.string().required() semantics for the validated ROM payload fields. */
function requireString(body, field) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) return 'value must be an object';
  const value = body[field];
  if (value === undefined || value === null) return `child "${field}" fails because ["${field}" is required]`;
  if (typeof value !== 'string') return `child "${field}" fails because ["${field}" must be a string]`;
  if (value.length === 0) return `child "${field}" fails because ["${field}" is not allowed to be empty]`;
  return null;
}

const sendValidation = (res, message) => sendAmzError(res, ValidationException, message);

/**
 * The ROM AWS-JSON handler. Ops are matched case-insensitively (X-Amz-Target prefix is
 * consumed by the router). Pass { controller } or { accountClient, robotClient,
 * certificates, onConnectionRequested, generatePair } to override the defaults.
 */
export function makeRomHandler(options = {}) {
  const controller = options.controller || new RomController({
    accountClient: options.accountClient || makeAccountClient(),
    robotClient: options.robotClient || makeRobotClient(),
    certificates: options.certificates,
    onConnectionRequested: options.onConnectionRequested,
    generatePair: options.generatePair,
  });

  return async function romHandler({ req, res, body, op }) {
    const b = body || {};
    const credentials = credentialsFrom(req);
    try {
      switch (op.toLowerCase()) {
        case 'create': {
          const invalid = requireString(b, 'friendlyId');
          if (invalid) return void sendValidation(res, invalid);
          const out = await controller.create({ aco: b.aco, friendlyId: b.friendlyId, ownerId: credentials.id, req });
          return void sendAmz(res, 200, out);
        }
        case 'setupserver': {
          const invalid = requireString(b, 'ipAddress');
          if (invalid) return void sendValidation(res, invalid);
          if (b.ipAddresses !== undefined && !Array.isArray(b.ipAddresses)) {
            return void sendValidation(res, 'child "ipAddresses" fails because ["ipAddresses" must be an array]');
          }
          const out = await controller.setupServer({
            friendlyId: credentials.friendlyId, ipAddress: b.ipAddress, ipAddresses: b.ipAddresses, req,
          });
          return void sendAmz(res, 200, out);
        }
        case 'setupclient': {
          const invalid = requireString(b, 'friendlyId');
          if (invalid) return void sendValidation(res, invalid);
          const out = await controller.setupClient({ friendlyId: b.friendlyId, ownerId: credentials.id, req });
          return void sendAmz(res, 200, out);
        }
        default:
          return void sendAmzError(res, ValidationException, `unknown ROM operation: ${op}`);
      }
    } catch (error) {
      if (error && error.romError) return void sendAmzError(res, error.romError, error.romError.message);
      throw error;
    }
  };
}
