// N-07: cover the ARCHIVED Dialogflow intent/entity catalog at runtime.
//
// The pinned agent export (jiboV2/pegasus@5c0a739, packages/parser/dialogflow/
// main_agent) is a complete archived artifact: 99 intent definitions (each with a
// real `responses[]` parameter schema), the 99 training-phrase files whose
// annotated segments carry the entity surface Dialogflow fills, and 89 entity
// definitions. The previous evidence treated this only as a hashed denominator
// (counts + sha256). These tests drive every archived intent and every archived
// entity through the preserved external-agent result structure instead.
//
//   fixtures/dialogflow-archived-agent.json  regenerated by
//   tools/deriveDialogflowArchivedAgent.mjs --write (and --check in CI-style
//   reruns), cross-checked here against the independently hashed
//   fixtures/dialogflow-agent-catalog.json.
//
// Response values are DERIVED from the intent's own training phrases
// (DialogflowClient.ts:100-104 copies response.result.metadata.intentName and
// response.result.parameters); no live Dialogflow round-trip is possible because
// the apiai service is dead.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createExternalAgentProvider, DECOY_INTENT, EXTERNAL_STATE } from '../src/externalAgents.js';
import { isFallbackResultValid, selectValidResult } from '../src/fallbackArbitration.js';

const archived = JSON.parse(readFileSync(new URL('./fixtures/dialogflow-archived-agent.json', import.meta.url)));
const catalog = JSON.parse(readFileSync(new URL('./fixtures/dialogflow-agent-catalog.json', import.meta.url)));

const ARCHIVED_REF = '5c0a7390539663ba749d360de348a428c088505c';
const DEFAULT_AGENT_RECORDING = { intent: 'doesJiboLikeThing', entities: { GeneralLikes: 'Penguin' } };

function archivedProvider() {
  const agents = { default: () => DEFAULT_AGENT_RECORDING };
  for (const intent of archived.intents) {
    agents[intent.name] = () => ({ intent: intent.name, entities: intent.derivedResponse.entities });
  }
  return createExternalAgentProvider({ enabled: true, accessToken: 'archived-token', agents });
}

test('the archived agent surface is re-derived from the pinned export and agrees with the hashed catalog', () => {
  assert.equal(archived.schema, 'phoenix.nlu.dialogflow-archived-agent');
  assert.equal(archived.provenance.ref, ARCHIVED_REF);
  assert.equal(archived.provenance.path, 'packages/parser/dialogflow/main_agent');
  assert.match(archived.provenance.agentJsonSha256, /^[0-9a-f]{64}$/);

  // The denominator is now re-derived, not hand-asserted.
  assert.equal(archived.intentCount, 99);
  assert.equal(archived.entityCount, 89);
  assert.equal(archived.annotatedEntityCount, 42);
  assert.equal(archived.intents.length, 99);
  assert.equal(archived.entities.length, 89);
  assert.equal(archived.annotatedEntities.length, 42);

  // Two independently derived fixtures must name exactly the same catalog, and
  // agree byte-for-byte on every archived file hash.
  assert.deepEqual(
    archived.intents.map(i => i.name).sort(),
    catalog.intents.map(i => i.intent).sort(),
  );
  assert.deepEqual(
    archived.entities.map(e => e.name).sort(),
    catalog.entities.map(e => e.entity).sort(),
  );
  const catalogIntentHashes = new Map(catalog.intents.map(i => [i.intent, i.sha256]));
  for (const intent of archived.intents) assert.equal(intent.sha256, catalogIntentHashes.get(intent.name));
  const catalogEntityHashes = new Map(catalog.entities.map(e => [e.entity, e.sha256]));
  for (const entity of archived.entities) assert.equal(entity.sha256, catalogEntityHashes.get(entity.name));

  // Every intent carries an archived response schema and a derived response.
  assert.equal(archived.intents.filter(i => i.responseParameters.length > 0).length, 86);
  assert.equal(archived.intents.filter(i => Object.keys(i.derivedResponse.entities).length > 0).length, 85);
  for (const intent of archived.intents) {
    assert.equal(intent.derivedResponse.intent, intent.name);
    assert.match(intent.sha256, /^[0-9a-f]{64}$/);
    assert.ok(intent.trainingPhraseCount > 0, `${intent.name} has no training phrases`);
    for (const entity of intent.attributedEntities) {
      assert.ok(archived.annotatedEntities.includes(entity), `${entity} not in the global annotated set`);
    }
  }
  assert.ok(archived.intents.some(i => i.name === DECOY_INTENT));
});

test('all 99 archived intents flow through the replaceable external provider envelope', () => {
  const provider = archivedProvider();
  assert.equal(provider.state, EXTERNAL_STATE.READY);

  const external = {};
  for (const intent of archived.intents) {
    external[intent.name] = { accessToken: `token-${intent.name}`, rules: [intent.name] };
  }
  const request = { text: 'do you like penguins', rules: ['launch'], external };
  const envelope = provider.handleNLU(request);

  assert.deepEqual(envelope.intent, DEFAULT_AGENT_RECORDING.intent);
  assert.equal(Object.keys(envelope.external).length, 99);

  for (const intent of archived.intents) {
    // Per-agent result preserves { rules, intent, entities } (DialogflowClient.ts:100-104)
    // for the archived intent name and its derived entity surface.
    assert.deepEqual(envelope.external[intent.name], {
      rules: [intent.name],
      intent: intent.name,
      entities: intent.derivedResponse.entities,
    });
  }

  // The 42 entity names the archived training data annotates all appear: 34
  // archived custom definitions plus 8 Dialogflow system entities (@sys.* and the
  // bare @given-name/@last-name aliases), which have no file under entities/.
  const annotated = new Set();
  for (const intent of archived.intents) for (const entity of intent.attributedEntities) annotated.add(entity);
  assert.equal(annotated.size, 42);
  assert.deepEqual([...annotated].sort(), archived.annotatedEntities);
  assert.equal(archived.annotatedCustomEntities.length, 34);
  assert.equal(archived.annotatedSystemEntities.length, 8);
  for (const entity of archived.annotatedCustomEntities) {
    assert.ok(archived.entities.some(e => e.name === entity), `${entity} is not an archived entity definition`);
  }
  for (const entity of archived.annotatedSystemEntities) {
    assert.ok(entity.startsWith('sys.') || entity === 'given-name' || entity === 'last-name', entity);
  }
});

test('the archived decoyIntent is rejected by arbitration while the other 98 survive', () => {
  const parserLow = { nlu: { intent: 'requestTellJiboContent', entities: { JiboContent: 'Joke' }, rules: ['launch'] }, priority: 'LOW' };
  let valid = 0;
  let decoy = 0;
  for (const intent of archived.intents) {
    const fallback = { intent: intent.name, entities: intent.derivedResponse.entities, rules: ['launch'] };
    if (intent.name === DECOY_INTENT) {
      assert.equal(isFallbackResultValid(fallback), false);
      assert.deepEqual(selectValidResult(parserLow, fallback), parserLow.nlu);
      decoy += 1;
    } else {
      assert.equal(isFallbackResultValid(fallback), true, `${intent.name} should be a valid fallback`);
      valid += 1;
    }
  }
  assert.equal(valid, 98);
  assert.equal(decoy, 1);
});
